# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default='tttttt', max_length=255),
        ),
    ]
