# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_article_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserProfile', unique=True),
        ),
    ]
